spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: demo
    password: demo

    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher